from .applyHygienicMeasures import ApplyHygienicMeasures
from .callElections import CallElections
from .closeAirport import CloseAirport
from .closeConnection import CloseConnection
from .deployMedication import DeployMedication
from .deployVaccine import DeployVaccine
from .developMedication import DevelopMedication
from .developVaccine import DevelopVaccine
from .endRound import EndRound
from .exertInfluence import ExertInfluence
from .launchCampaign import LaunchCampaign
from .putUnderQuarantine import PutUnderQuarantine
